name: Redeploy Entire Railway Repository

on:
  schedule:
    - cron: "0 */1 * * * *" # Runs every 4 hours

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Redeploy Entire Project
        run: railway up --detach
