name: Restart Railway Server

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo 'export PATH="$HOME/.railway/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --token $RAILWAY_TOKEN

      - name: Stop Railway Service
        run: railway down

      - name: Start Railway Service
        run: railway up
