name: Restart Railway Server

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Stop Railway Service
        run: railway down

      - name: Start Railway Service
        run: railway up
