name: Auto Redeploy

on:
  schedule:
    - cron: "0 */1 * * *" # Runs every 1 hour

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Redeploy Project
        run: railway up
