name: Restart Railway Server

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: echo "${RAILWAY_TOKEN}" | railway login --key -

      - name: Restart Railway Service
        run: railway up --detach
